// Create web server
// npm install express
// npm install body-parser
// npm install mongoose
// npm install nodemon
// npm install dotenv
// npm install cors
// npm install axios
// npm install morgan